### ISSUE TITLE
Add a filter by vaccine type 

### ISSUE THREAD

**Issue by freakomonk** [arjunlalb/cowin-monitor#1]
**Is your feature request related to a problem? Please describe.**
A lot of people in a few states got their initial dose of covaxin and now are waiting for the stock to be available to get second dose. 

Would be lot helpful if we can search based on vaccine type

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arjunlalb** [comment]
@freakomonk You can now filter by vaccine type.
